settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: spotify-headphone-party
  path: .
  commands:
    build:
      status: true
      method: go build
      args:
        - '-o debug'
        - '-gcflags="all=-N"'
        - './'
    run:
      status: true
      method : /go/bin/dlv
  args:
    - exec
    - ./debug
    - --headless=true
    - --listen=:2345
    - --api-version=2
    - --accept-multiclient
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
